name: Rust
on:
  push:
    branches:
      - main
jobs:      
  todos_macos:
    runs-on: macOS-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
    - uses: actions/checkout@master
    - name: Build binary
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.14
      run: cargo build --verbose --release
    - name: Open binary via double-click
      run: chmod +x target/release/zr-alshasha
    - name: Archive todos binary
      uses: actions/upload-artifact@v1
      with:
        name: todos-x86_64-apple-darwin
        path: target/release/zr-alshasha
